apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: opa
  labels:
    name: opa
spec:
  selector:
    matchLabels:
      app: opa
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opa
    spec:
      initContainers:
        - name: initpolicy
          image: openpolicyagent/kube-mgmt:7.1.1
          imagePullPolicy: IfNotPresent
          resources:
            {}
          command:
          - /bin/sh
          - -c
          - |
            tr -dc 'A-F0-9' < /dev/urandom | dd bs=1 count=32 2>/dev/null > /bootstrap/mgmt-token
            TOKEN=`cat /bootstrap/mgmt-token`
            cat > /bootstrap/authz.rego <<EOF
            package system.authz
            default allow = false
            # Allow anonymous access to the default policy decision.
            allow { input.path = [""]; input.method = "POST" }
            allow { input.path = [""]; input.method = "GET" }
            # This is only used for health check in liveness and readiness probe
            allow { input.path = ["health"]; input.method = "GET" }
            allow { input.identity == "$TOKEN" }
            EOF
          volumeMounts:
            - name: certs
              readOnly: true
              mountPath: /certs
            - name: config
              readOnly: true
              mountPath: /config
            - name: bootstrap
              readOnly: true
              mountPath: /bootstrap
      containers:
      - name: kube-mgmt
        image: openpolicyagent/kube-mgmt:7.1.1
        imagePullPolicy: Always
        env:
        resources:
          limits:
            cpu: 25m
            memory: 128Mi
          requests:
            cpu: 25m
            memory: 128Mi
        args:
          - --opa-auth-token-file=/bootstrap/mgmt-token
          - --opa-url=https://127.0.0.1:8181/v1
          - --opa-allow-insecure
          - --namespaces=default
          - --enable-data=true
          - --enable-policies=true
          - --replicate-path=kubernetes
        volumeMounts:
          - name: bootstrap
            readOnly: true
            mountPath: /bootstrap
      - name: opa
        args:
          - "run"
          - "--server"
          - "--addr" 
          - ":8181" 
          - "--log-format" 
          - "text" 
          # - "--set" 
          # - "decision_logs.console=true" 
          - "--set" 
          - "bundles.play.polling.long_polling_timeout_seconds=45" 
          - "--set" 
          - "services.play.url=https://play.openpolicyagent.org" 
          - "--set" 
          - "bundles.play.resource=bundles/Ks7me35y74"
        image: openpolicyagent/opa:0.46.1
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
        resources:
          limits:
            cpu: 50m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 256Mi
        ports:
        - containerPort: 8181
          name: https
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            scheme: HTTP
            port: 8181
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            scheme: HTTP
            port: 8181
          initialDelaySeconds: 3
          periodSeconds: 5
        volumeMounts:
          - name: bootstrap
            readOnly: true
            mountPath: /bootstrap
      volumes:
        - name: certs
          secret:
            secretName: opa-kube-mgmt-cert
        - name: config
          secret:
            secretName: opa-kube-mgmt-config
        - name: bootstrap
          emptyDir: {}