apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: opa
  labels:
    name: opa
spec:
  selector:
    matchLabels:
      app: opa
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
      - name: opa
        args:
          - "run"
          - "--server"
          - "--addr" 
          - ":8181" 
          - "--log-format" 
          - "text" 
          - "--set" 
          - "decision_logs.console=true" 
          - "--set" 
          - "bundles.play.polling.long_polling_timeout_seconds=45" 
          - "--set" 
          - "services.play.url=https://play.openpolicyagent.org" 
          - "--set" 
          - "bundles.play.resource=bundles/JPQeObdth8"
# {{- if .Values.opa }}
#           - "--config-file=/config/config.yaml"
# {{- end }}
          # - "--tls-cert-file=/certs/tls.crt"
          # - "--tls-private-key-file=/certs/tls.key"
          # - "--addr=0.0.0.0:{{ .Values.port }}"
          # - "--log-level={{ .Values.logLevel }}"
          # - "--log-format={{ .Values.logFormat }}"
# {{- if .Values.authz.enabled }}
#           - "--authentication=token"
#           - "--authorization=basic"
#           - "/authz/authz.rego"
#           - "--ignore=.*"
# {{- end }}
# {{- if .Values.mgmt.enabled }}
#             - "--insecure-addr=127.0.0.1:8181"
# {{- end }}
        image: openpolicyagent/opa:0.46.1
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
        resources:
          limits:
            cpu: 50m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 256Mi
        ports:
        - containerPort: 8181
          name: https
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            scheme: HTTP
            port: 8181
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            scheme: HTTP
            port: 8181
          initialDelaySeconds: 3
          periodSeconds: 5
      #   volumeMounts:
      #     - name: nginx-conf
      #       mountPath: /etc/nginx/nginx.conf
      #       subPath: nginx.conf
      #       readOnly: true
      # volumes:
      # - name: nginx-conf
      #   configMap:
      #     name: nginx-conf
      #     items:
      #       - key: nginx.conf
      #         path: nginx.conf
